#!/usr/bin/env bash
set -u

DEFAULT_URL="https://www.bilibili.com/video/BV1zoGv6NE2q"
PROJECT_ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
COOKIE_FILE="${BILIBILI_COOKIES_FILE:-$PROJECT_ROOT/local-bilibili.cookies.txt}"
OUTPUT_DIR="${BILIBILI_TEST_OUTPUT_DIR:-$PROJECT_ROOT/local-bilibili-test}"
URL="$DEFAULT_URL"
DO_VIDEO_DOWNLOAD=0

BILIBILI_HEADERS=(
  --add-header "Referer: https://www.bilibili.com"
  --add-header "Origin: https://www.bilibili.com"
  --user-agent "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/130.0.0.0 Safari/537.36"
)

print_help() {
  cat <<'EOF'
用法:
  scripts/test_bilibili_download.sh [选项] [B站URL]

选项:
  --video-download       额外测试完整视频下载；默认只测元数据和音频下载
  --cookie-file PATH     使用指定 Netscape cookies.txt 文件
  --output-dir PATH      诊断输出目录，默认 local-bilibili-test/
  -h, --help             显示帮助

Cookie 输入:
  1. 推荐把 B 站 Cookie 保存到 local-bilibili.cookies.txt。
  2. 也可以临时设置 COOKIE='SESSDATA=...; bili_jct=...; ...'，
     脚本会自动转换成 Netscape cookies.txt，且不会把 Cookie 打印到终端。

示例:
  COOKIE='SESSDATA=...; bili_jct=...' scripts/test_bilibili_download.sh \
    'https://www.bilibili.com/video/BV1zoGv6NE2q'

  scripts/test_bilibili_download.sh --video-download \
    --cookie-file local-bilibili.cookies.txt \
    'https://www.bilibili.com/video/BV1zoGv6NE2q'
EOF
}

while [[ $# -gt 0 ]]; do
  case "$1" in
    --video-download)
      DO_VIDEO_DOWNLOAD=1
      shift
      ;;
    --cookie-file)
      if [[ $# -lt 2 ]]; then
        echo "错误: --cookie-file 需要路径参数" >&2
        exit 2
      fi
      COOKIE_FILE="$2"
      shift 2
      ;;
    --output-dir)
      if [[ $# -lt 2 ]]; then
        echo "错误: --output-dir 需要路径参数" >&2
        exit 2
      fi
      OUTPUT_DIR="$2"
      shift 2
      ;;
    -h|--help)
      print_help
      exit 0
      ;;
    -*)
      echo "错误: 未知选项 $1" >&2
      print_help >&2
      exit 2
      ;;
    *)
      URL="$1"
      shift
      ;;
  esac
done

mkdir -p "$OUTPUT_DIR"
OUTPUT_DIR="$(cd "$OUTPUT_DIR" && pwd)"

log() {
  printf '\n== %s ==\n' "$1"
}

write_cookie_file_from_header() {
  if [[ -z "${COOKIE:-}" || -s "$COOKIE_FILE" ]]; then
    return 0
  fi

  mkdir -p "$(dirname "$COOKIE_FILE")"
  COOKIE_FILE="$COOKIE_FILE" python - <<'PY'
from http.cookies import SimpleCookie
from pathlib import Path
import os
import time

cookie_header = os.environ.get("COOKIE", "")
cookie_file = Path(os.environ["COOKIE_FILE"])
cookie = SimpleCookie()
cookie.load(cookie_header)
expires = int(time.time()) + 180 * 24 * 60 * 60

lines = [
    "# Netscape HTTP Cookie File",
    "# Generated by scripts/test_bilibili_download.sh from COOKIE env.",
]
for name, morsel in cookie.items():
    value = morsel.value
    if not name or not value:
        continue
    lines.append(f".bilibili.com\tTRUE\t/\tTRUE\t{expires}\t{name}\t{value}")

cookie_file.write_text("\n".join(lines) + "\n", encoding="utf-8")
PY
  chmod 600 "$COOKIE_FILE"
}

cookie_args=()
prepare_cookie_args() {
  write_cookie_file_from_header
  if [[ -s "$COOKIE_FILE" ]]; then
    cookie_args=(--cookies "$COOKIE_FILE")
    echo "Cookie 文件: $COOKIE_FILE"
    if awk '$0 !~ /^#/ && $6 == "SESSDATA" { found = 1 } END { exit found ? 0 : 1 }' "$COOKIE_FILE"; then
      echo "Cookie 检查: 已找到 SESSDATA"
    else
      echo "Cookie 检查: 未找到 SESSDATA，可能只能访问公开信息"
    fi
  else
    cookie_args=()
    echo "Cookie 文件: 未提供"
  fi
}

run_step() {
  local name="$1"
  shift
  local stdout_file="$OUTPUT_DIR/$name.stdout"
  local stderr_file="$OUTPUT_DIR/$name.stderr"
  local status_file="$OUTPUT_DIR/$name.status"

  log "$name"
  echo "命令输出: $stdout_file"
  echo "错误输出: $stderr_file"
  (
    cd "$PROJECT_ROOT"
    "$@"
  ) >"$stdout_file" 2>"$stderr_file"
  local status=$?
  echo "$status" > "$status_file"
  echo "exit_code=$status"

  if [[ -s "$stderr_file" ]]; then
    echo "-- stderr 摘要 --"
    grep -E "ERROR|WARNING|HTTP Error|Precondition|Extracting|Downloading|cookie|Cookie|unsupported|Unsupported" "$stderr_file" | tail -40 || tail -40 "$stderr_file"
  fi

  return "$status"
}

summarize_json() {
  local json_path="$1"
  python - "$json_path" <<'PY'
import json
import sys
from pathlib import Path

path = Path(sys.argv[1])
text = path.read_text(encoding="utf-8", errors="replace").strip()
if not text or text == "null":
    print("JSON 摘要: stdout 为空或 null")
    raise SystemExit(1)

try:
    data = json.loads(text)
except Exception as exc:
    print(f"JSON 摘要: 解析失败: {exc}")
    raise SystemExit(1)

if not isinstance(data, dict):
    print(f"JSON 摘要: 顶层类型不是 object: {type(data).__name__}")
    raise SystemExit(1)

for key in ("id", "title", "uploader", "webpage_url", "duration"):
    print(f"{key}: {data.get(key)!r}")

subtitles = data.get("subtitles") or {}
automatic = data.get("automatic_captions") or {}
formats = data.get("formats") or []
print("subtitles keys:", list(subtitles.keys()))
print("automatic_captions keys:", list(automatic.keys())[:20])
print("formats count:", len(formats) if isinstance(formats, list) else 0)
PY
}

log "基础环境"
echo "项目目录: $PROJECT_ROOT"
echo "URL: $URL"
echo "输出目录: $OUTPUT_DIR"
echo "完整视频下载: $DO_VIDEO_DOWNLOAD"
command -v uv || true
uv --version || true

log "依赖版本"
(
  cd "$PROJECT_ROOT"
  UV_CACHE_DIR=.uv-cache uv run python - <<'PY'
import importlib.util
import subprocess

for name in ("yt_dlp", "curl_cffi", "secretstorage", "cryptography"):
    print(f"{name}: {bool(importlib.util.find_spec(name))}")
try:
    completed = subprocess.run(["yt-dlp", "--version"], text=True, capture_output=True, check=False)
    print("yt-dlp:", completed.stdout.strip() or completed.stderr.strip())
except FileNotFoundError:
    print("yt-dlp: not found")
PY
)

log "Cookie"
prepare_cookie_args

metadata_status=1
run_step metadata \
  env UV_CACHE_DIR=.uv-cache uv run yt-dlp \
    --dump-single-json \
    --skip-download \
    --no-playlist \
    --no-warnings \
    "${cookie_args[@]}" \
    "${BILIBILI_HEADERS[@]}" \
    "$URL"
metadata_status=$?
summarize_json "$OUTPUT_DIR/metadata.stdout" || true

run_step metadata_impersonate_edge \
  env UV_CACHE_DIR=.uv-cache uv run yt-dlp \
    --impersonate edge-99 \
    --dump-single-json \
    --skip-download \
    --no-playlist \
    --no-warnings \
    "${cookie_args[@]}" \
    "${BILIBILI_HEADERS[@]}" \
    "$URL" || true
summarize_json "$OUTPUT_DIR/metadata_impersonate_edge.stdout" || true

run_step audio_download \
  env UV_CACHE_DIR=.uv-cache uv run yt-dlp \
    --extract-audio \
    --audio-format m4a \
    --print after_move:filepath \
    -o "$OUTPUT_DIR/audio.%(ext)s" \
    --no-playlist \
    "${cookie_args[@]}" \
    "${BILIBILI_HEADERS[@]}" \
    "$URL" || true

if [[ "$DO_VIDEO_DOWNLOAD" -eq 1 ]]; then
  run_step video_download \
    env UV_CACHE_DIR=.uv-cache uv run yt-dlp \
      -f "bestvideo+bestaudio/best" \
      --merge-output-format mp4 \
      -o "$OUTPUT_DIR/%(id)s.%(ext)s" \
      --no-playlist \
      "${cookie_args[@]}" \
      "${BILIBILI_HEADERS[@]}" \
      "$URL" || true
fi

log "km ingest"
(
  cd "$PROJECT_ROOT"
  printf '{"url":"%s","mode":"ingest"}\n' "$URL" |
    UV_CACHE_DIR=.uv-cache uv run km ingest
) >"$OUTPUT_DIR/km-ingest.stdout" 2>"$OUTPUT_DIR/km-ingest.stderr"
km_status=$?
echo "exit_code=$km_status"
echo "stdout: $OUTPUT_DIR/km-ingest.stdout"
echo "stderr: $OUTPUT_DIR/km-ingest.stderr"
head -80 "$OUTPUT_DIR/km-ingest.stdout" || true
if [[ -s "$OUTPUT_DIR/km-ingest.stderr" ]]; then
  echo "-- km stderr 摘要 --"
  tail -80 "$OUTPUT_DIR/km-ingest.stderr"
fi

log "结论提示"
if [[ "$metadata_status" -eq 0 ]]; then
  echo "metadata 阶段成功；如果 km ingest 失败，问题更可能在项目管道后续步骤。"
else
  echo "metadata 阶段失败；优先查看 $OUTPUT_DIR/metadata.stderr 中的 HTTP 412、Cookie 或风控信息。"
fi
echo "完整日志目录: $OUTPUT_DIR"
